### ISSUE TITLE
Where are the native components?

### ISSUE THREAD

**Issue by tstr007** [luanon404/Moe-Moe#1]
Thank you for this project. 
Where to obtain native components [libstandalonelibwebviewchromium.so] ?

**Comment by luanon404** [comment]
Because github does not allow files > 50m, and I am rebuilding the project, so i remove it for easy push

**Comment by luanon404** [comment]
you can download it at https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2Fxueqiya%2FAwDemo%2Ftree%2Fmaster%2Faw_contents%2Fsrc%2Fmain%2FjniLibs

**Comment by luanon404** [comment]
Download `jniLibs.zip` and unzip it, then put into `aw_chromium/src/main/jniLibs`.

**Comment by luanon404** [comment]
this project still rebuilding so you should not use it, maybe after i convert all java code to kotlin (google code > messy)
