### ISSUE TITLE
Question: Why use AwChromium instead of Android WebView

### ISSUE THREAD

**Issue by jianglei12138** [luanon404/Moe-Moe#2]
Hi luanon404:

AWChromium is a fantastic project. But I have a Problem.
may be we can proxy android.webkit.WebViewFactory#sProviderInstance to use AWChromium, other project which want integrate AWChromium can using android WebView directly.

**Comment by luanon404** [comment]
Because android.webkit.WebView imposes significant limitations on permissions, you can't access iframe src or similar elements. It functions as a controller but restricting permissions may seem impractical. As a result, I switched to Chromium WebView. You can think of it as 'Android WebView Chromium -> Android WebKit -> My App,' which is why I chose to use Chromium WebView.

**Comment by luanon404** [comment]
and i will build my webdriver based on this, but u also use if u want, but not now, im trying to fix too many problems with android studio.

**Comment by luanon404** [comment]
to answer your question, my answer is "i dont know", why ? just fast look at chromium source, they had so many example code, com.android.google.*, org.chromium.android_webview.test.*, ... i dont know but some example use old android code, like android.webkit.WebViewFactory, androidx dont like it, so i dont know, im trying to push to version 120, then rebuild it later

**Comment by luanon404** [comment]
![image](https://github.com/luanon404/AWChromium/assets/71830807/d8882ca4-d09e-4218-94ac-52b86c0d23e7)
imagine u can access iframe with 1 line of code, That's so great!!!

**Comment by luanon404** [comment]
size maybe increase but u can do too many things with it

**Comment by jianglei12138** [comment]
Thanks for your reply. I'll try make a standalone webview library base on chromium & android.webkit.WebView
aims to solve the webview differences between different android os versions.

I'll post here once I finished it.

Thanks!

**Comment by luanon404** [comment]
> Thanks for your reply. I'll try make a standalone webview library base on chromium & android.webkit.WebView aims to solve the webview differences between different android os versions.
> 
> I'll post here once I finished it.
> 
> Thanks!

u should not bro

**Comment by luanon404** [comment]
android webview chromium can use in any android version, but I only use for android >= 24

**Comment by luanon404** [comment]
just use one, also it took 13 hours to build lib webview

**Comment by luanon404** [comment]
but if u want, then u can get code from here https://chromium.googlesource.com/chromium/src/out/+/refs/heads/main/android-Debug/gen/android_webview/test/webview_instrumentation_apk/generated_java/input_srcjars/org/jni_zero/GEN_JNI.java, like some old android library

**Comment by luanon404** [comment]
@jianglei12138 i updated to version 120, u can create pull request if u want instead of start from nothing

**Comment by luanon404** [comment]
![image](https://github.com/luanon404/Moe-Moe/assets/71830807/1a32ad0c-1ba9-4c39-a824-a41380398e33)

**Comment by jianglei12138** [comment]
Oh thanks, I'll try it when finish what I'm doing
