### ISSUE TITLE
Task :aw_chromium:extractReleaseAnnotations FAILED

### ISSUE THREAD

**Issue by tstr007** [luanon404/Moe-Moe#4]
Debug builds are working fine, While Release build fails with this error everytime 
`Task :aw_chromium:extractReleaseAnnotations FAILED`

more details 

` 
Task failed with an exception.
* What went wrong:
Execution failed for task ':aw_chromium:extractReleaseAnnotations'.
> A failure occurred while executing com.android.build.gradle.internal.lint.AndroidLintWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
`

**Comment by luanon404** [comment]
maybe this cause that error https://stackoverflow.com/a/40457908

**Comment by luanon404** [comment]
i will try it later, but its true because i saw some annotation like @IntDef({}) maybe try delete it?

**Comment by luanon404** [comment]
also about black screen i found when play video, its webview issue, i tried all solution on stackoverflow but sometime it play and sometime not, also about full screen issue, idk why it say `Fullscreen not support` in javascript console, onShowCustomView and onHideCustomView not called

**Comment by tstr007** [comment]
> maybe this cause that error https://stackoverflow.com/a/40457908

yes there is empty 
`@IntDef({
})`
here https://github.com/luanon404/Moe-Moe/blob/36a131b77a8f8620e041a7ea3c64a0100132c00e/aw_chromium/src/main/java/org/chromium/media/mojom/SampleFormat.java#L20
https://github.com/luanon404/Moe-Moe/blob/36a131b77a8f8620e041a7ea3c64a0100132c00e/aw_chromium/src/main/java/org/chromium/media/mojom/WatchTimeKey.java#L20
https://github.com/luanon404/Moe-Moe/blob/36a131b77a8f8620e041a7ea3c64a0100132c00e/aw_chromium/src/main/java/org/chromium/media/mojom/CdmSessionType.java#L20
https://github.com/luanon404/Moe-Moe/blob/36a131b77a8f8620e041a7ea3c64a0100132c00e/aw_chromium/src/main/java/org/chromium/media/mojom/AudioCodecProfile.java#L20
https://github.com/luanon404/Moe-Moe/blob/36a131b77a8f8620e041a7ea3c64a0100132c00e/aw_chromium/src/main/java/org/chromium/media/mojom/VideoCodecProfile.java#L20
https://github.com/luanon404/Moe-Moe/blob/36a131b77a8f8620e041a7ea3c64a0100132c00e/aw_chromium/src/main/java/org/chromium/media/mojom/MediaContainerName.java#L20

**Comment by tstr007** [comment]
> also about black screen i found when play video, its webview issue, i tried all solution on stackoverflow but sometime it play and sometime not, also about full screen issue, idk why it say `Fullscreen not support` in javascript console, onShowCustomView and onHideCustomView not called

You're doing great work 
May I suggest you see this project 
https://github.com/shimohq/BisonView
it's the nearly same as here 
Where you keep everything as original and updated to the latest version of chromium 
- If only you can remove un needed files from .so jnilibs as possible to reduce size

**Comment by luanon404** [comment]
its imposible, but u can split abi

**Comment by tstr007** [comment]
> its imposible, but u can split abi

i know this already, Thanks for your efforts .

**Comment by luanon404** [comment]
> > also about black screen i found when play video, its webview issue, i tried all solution on stackoverflow but sometime it play and sometime not, also about full screen issue, idk why it say `Fullscreen not support` in javascript console, onShowCustomView and onHideCustomView not called
> 
> You're doing great work May I suggest you see this project https://github.com/shimohq/BisonView it's the nearly same as here Where you keep everything as original and updated to the latest version of chromium
> 
>     * If only you can remove un needed files from .so jnilibs as possible to reduce size

that project look cool, but i think no one need too many files

**Comment by luanon404** [comment]
just webview and webviewclient

**Comment by tstr007** [comment]
> just webview and webviewclient

Agreed.

**Comment by luanon404** [comment]
> > just webview and webviewclient
> 
> Agreed.

but i have one question, i saw u folk so many webview project, because hobby or something?

**Comment by luanon404** [comment]
webview is only the part of my project, my goal is android webdriver

**Comment by luanon404** [comment]
so i wonder..

**Comment by luanon404** [comment]
![image](https://github.com/luanon404/Moe-Moe/assets/71830807/f302fe36-1619-41a6-b689-b9f22ab68aed)
i think its website problem not webview....

**Comment by tstr007** [comment]
> > > just webview and webviewclient
> > 
> > 
> > Agreed.
> 
> but i have one question, i saw u folk so many webview project, because hobby or something?

I've been tracking this better webview since 
https://github.com/crosswalk-project
to find better webview as I do create and work with games created mainly for web 
and this needs better rendering capabilities and even some devices have so webview installed by default 
In the late years newer version of webview are installed and frequently updated by play store as it is used by many other apps like Gmail.
I have to choose whether to support older devices or not. 
Right now it's not cool to add many MB of size to an application to use an program which is already available on most devices and frequently updated. 
But in some rare occasions the default webview implementation is not enough.
Mozilla has open source geckoview but i'm not familiar with is https://github.com/mozilla/geckoview

**Comment by tstr007** [comment]
> ![image](https://user-images.githubusercontent.com/71830807/279404033-f302fe36-1619-41a6-b689-b9f22ab68aed.png) i think its website problem not webview....

yes i see no fullscreen button or controls on video screen, if you mean no fullscreen

**Comment by luanon404** [comment]
no i mean black screen

**Comment by luanon404** [comment]
full screen only open full of webview layout not phone

**Comment by luanon404** [comment]
i think i can fix this, because webview and webviewclient i took from other not mine so i think something wrong, playing video with example activity not show [ERROR:tile_manager.cc(980)] WARNING: tile memory limits exceeded, some content may not draw

**Comment by tstr007** [comment]
> no i mean black screen

I tested with youtube several time 
and some times it work and some times black screen

**Comment by tstr007** [comment]
> i think i can fix this, because webview and webviewclient i took from other not mine so i think something wrong, playing video with example activity not show [ERROR:tile_manager.cc(980)] WARNING: tile memory limits exceeded, some content may not draw

may be because when the video plays correctly i don't see this ERROR in log

**Comment by luanon404** [comment]
> > i think i can fix this, because webview and webviewclient i took from other not mine so i think something wrong, playing video with example activity not show [ERROR:tile_manager.cc(980)] WARNING: tile memory limits exceeded, some content may not draw
> 
> may be because when the video plays correctly i don't see this ERROR in log

yes u right

**Comment by luanon404** [comment]
maybe setting or client wrong

**Comment by luanon404** [comment]
mine: black screen but can play sound
chromium: block m3u8 but can play other with video and sound

**Comment by luanon404** [comment]
my config look good, black screen is only problem

**Comment by tstr007** [comment]
i appreciate your efforts and wish you all the best :)

**Comment by luanon404** [comment]
> > > just webview and webviewclient
> > 
> > 
> > Agreed.
> 
> but i have one question, i saw u folk so many webview project, because hobby or something?

@tstr007 can u answer? ._.

**Comment by luanon404** [comment]
oh u did my mistake

**Comment by luanon404** [comment]
i think i found a problem

**Comment by luanon404** [comment]
but did u try this ? https://github.com/shimohq/BisonView , did full screen feature work?

**Comment by luanon404** [comment]
> > > > just webview and webviewclient
> > > 
> > > 
> > > Agreed.
> > 
> > 
> > but i have one question, i saw u folk so many webview project, because hobby or something?
> 
> I've been tracking this better webview since https://github.com/crosswalk-project to find better webview as I do create and work with games created mainly for web and this needs better rendering capabilities and even some devices have so webview installed by default In the late years newer version of webview are installed and frequently updated by play store as it is used by many other apps like Gmail. I have to choose whether to support older devices or not. Right now it's not cool to add many MB of size to an application to use an program which is already available on most devices and frequently updated. But in some rare occasions the default webview implementation is not enough. Mozilla has open source geckoview but i'm not familiar with is https://github.com/mozilla/geckoview

i tried geckoview, but its very ...., they didnt update docs for long time, also extension not work at all

**Comment by luanon404** [comment]
i fixed and now chromium example activity working with all video type 
![image](https://github.com/luanon404/Moe-Moe/assets/71830807/b1861f83-7e78-45b6-9dc4-b5e99b0e8851)

**Comment by luanon404** [comment]
I think there are 2 reasons for the black screen, 1 is because it is really overloaded, 2 is maybe the function is called many times leading to a conflict

**Comment by tstr007** [comment]
> but did u try this ? https://github.com/shimohq/BisonView , did full screen feature work?

no full screen feature did not work , however i was unable to test their final release as they didn't provide jnilibs .so filses 
other than that everything works nicely like video from many websites and mp4 , hls etc

**Comment by tstr007** [comment]
> > > > > just webview and webviewclient
> > > > 
> > > > 
> > > > Agreed.
> > > 
> > > 
> > > but i have one question, i saw u folk so many webview project, because hobby or something?
> > 
> > 
> > I've been tracking this better webview since https://github.com/crosswalk-project to find better webview as I do create and work with games created mainly for web and this needs better rendering capabilities and even some devices have so webview installed by default In the late years newer version of webview are installed and frequently updated by play store as it is used by many other apps like Gmail. I have to choose whether to support older devices or not. Right now it's not cool to add many MB of size to an application to use an program which is already available on most devices and frequently updated. But in some rare occasions the default webview implementation is not enough. Mozilla has open source geckoview but i'm not familiar with is https://github.com/mozilla/geckoview
> 
> i tried geckoview, but its very ...., they didnt update docs for long time, also extension not work at all

agreed

**Comment by tstr007** [comment]
> i fixed and now chromium example activity working with all video type ![image](https://user-images.githubusercontent.com/71830807/279427529-b1861f83-7e78-45b6-9dc4-b5e99b0e8851.png)

great. 
see what you can do about this release issue Task :aw_chromium:extractReleaseAnnotations FAILED

**Comment by luanon404** [comment]
> > i fixed and now chromium example activity working with all video type ![image](https://user-images.githubusercontent.com/71830807/279427529-b1861f83-7e78-45b6-9dc4-b5e99b0e8851.png)
> 
> great. see what you can do about this release issue Task :aw_chromium:extractReleaseAnnotations FAILED

i will try it after finish school

**Comment by luanon404** [comment]
| 1 | 2 | 3 |
| --- | --- | --- |
| ![image](https://github.com/luanon404/Moe-Moe/assets/71830807/b6cdb5ec-b3ec-4e3a-8e03-df7b0fe52553) | ![image](https://github.com/luanon404/Moe-Moe/assets/71830807/61346ad8-ab08-4714-b7e8-ea518cacb610) | ![image](https://github.com/luanon404/Moe-Moe/assets/71830807/d916ca25-56df-4428-9efd-65ebe09959ab) |

**Comment by luanon404** [comment]
full screen only fit webview layout not full screen, also i tried too many way but look like yt dont like it

**Comment by luanon404** [comment]
I dont know why it not call onShowCustomView and onHideCustomView

**Comment by luanon404** [comment]
and about release, there is no problem for me
![image](https://github.com/luanon404/Moe-Moe/assets/71830807/f859b8d2-7fdc-4f65-b5b9-1111aac25d52)
![image](https://github.com/luanon404/Moe-Moe/assets/71830807/6691971c-41e5-458f-b0a2-e12cda775ce8)

**Comment by luanon404** [comment]
maybe u android studio too old? 😂😂

**Comment by luanon404** [comment]
> I dont know why it not call onShowCustomView and onHideCustomView

no call = cant full screen

**Comment by luanon404** [comment]
> > I dont know why it not call onShowCustomView and onHideCustomView
> 
> no call = cant full screen

i have no idea, i think i cant fix this

**Comment by luanon404** [comment]
this issue problem is cant build release but i have no problem with this so i will close this
